### ISSUE TITLE
Enforce "Hosted by OCF" banners

### ISSUE THREAD

**Issue by fydai** [ocf/projects#16]
https://ocf.io/rt/81

**Comment by emmatyping** [comment]
I believe this is pretty much resurrecting https://github.com/ocf/utils/pull/80

**Comment by dkess** [comment]
I'd argue that this project isn't worth doing. It's really hard / impossible to avoid false positives, and we're not interested in proactively going after non-compliant sites anyways.

The standard way of dealing with banner enforcement is to not make a fuss about it, but if a group comes to staff hours and asks for help with their website (or emails help@), and we notice that they don't have the banner, we politely ask them to add the banner after helping them.

**Comment by emmatyping** [comment]
Yeah I think that is a reasonable stance. If someone wants to do this for fun, go ahead, but I think I agree doing this in a semi-automatic fashion still requires a lot of manual sifting which makes it too much work.
