### ISSUE TITLE
Torrents @ OCF

### ISSUE THREAD

**Issue by ethanhs** [ocf/projects#34]

**Comment by dkess** [comment]
What is this?

**Comment by ethanhs** [comment]
Oh the idea was we could seed Debian, Ubuntu, Raspbian etc ISOs.

**Comment by nikhiljha** [comment]
This would probably get us in trouble, so closing.

**Comment by singingtelegram** [comment]
I'm not sure why that's the case. Torrenting isn't by itself illegal, and it should be perfectly fine to distribute (actual) Linux ISOs. With 10GbE networking @ EWDC on our mirrors server, it might be worth it to seed ISOs of various distros.
