### ISSUE TITLE
Matrix Server

### ISSUE THREAD

**Issue by encadyma** [ocf/projects#35]
Having a Matrix server would be a neat communications addition to the OCF. Some thoughts:

- Work on this is being done in bolide.ocf.berkeley.edu.
- We have multiple deployment options: install from source (pip) or Debian repositories, use an Ansible playbook (https://github.com/spantaleev/matrix-docker-ansible-deploy), or use docker-compose (fydai's idea after seeing the Ansible playbook). The latter two would provide more features, including having Docker containers for WebRTC, the Riot web client, etc. 
- Currently leaning towards the docker-compose option, with potential change to Kubernetes
- Configuration on the Matrix server itself still needs to be determined...

Docker containers we would want (from the Matrix Ansible repo):
- Synapse https://hub.docker.com/r/matrixdotorg/synapse/
- CoTURN (VoIP) https://hub.docker.com/r/instrumentisto/coturn/
- Riot Web Client https://hub.docker.com/r/bubuntux/riot-web/
- IRC Bridge https://hub.docker.com/r/tedomum/matrix-appservice-irc/

Debatable:
- Matrix Identity Server https://hub.docker.com/r/kamax/mxisd/ (would we need this?)
- Email to Matrix https://hub.docker.com/r/devture/email2matrix/
- Dimension (Chat Integrations Manager) https://hub.docker.com/r/turt2live/matrix-dimension (Integrations would be nice, but leaving this here for now.)

Connections needed for existing services:
- PostgreSQL
- Email server
- (optional) Ceph or some S3-compliant service

Feel free to add thoughts on configuration options or more.

Federation tester: https://federationtester.matrix.org/

**Comment by dkess** [comment]
I'd recommend doing all of this on Kubernetes. We can make you a development environment to experiment in.

**Comment by dkess** [comment]
Also, we don't need an identity server (all that does is convert phone numbers or other third-party identifiers to Matrix usernames). VoIP is also not necessary for us (unless you have a specific interest in it, in which case go for it).

One of the trickier parts for this will be file uploads. It should be fine to start off with an NFS-based system (see how Kanboard does this) and then move to Ceph object storage when we're able to.

**Comment by encadyma** [comment]
We're in prod! https://github.com/ocf/matrix
