### ISSUE TITLE
moffle → whitequark/irclogger

### ISSUE THREAD

**Issue by nikhiljha** [ocf/projects#38]
It shouldn't be too hard to make a parser to import the data. (famous last words)

Something like https://github.com/whitequark/irclogger/blob/master/scripts/clogimport.rb but changed a little bit to work with ZNC logs would be nice. I can do it once I have access to moffle data.

**Comment by nikhiljha** [comment]
Started writing an importer: https://github.com/nikhiljha/irclogger/blob/master/scripts/moffleimport.rb

I have 2011-05-05 to 2018-08-26 for #rebuild. Does moffle have any other logs?

**Comment by nikhiljha** [comment]
Status: 
Imported 2011-05-05 to 2018-08-26 🥳 
Need logs for 2018-08-27 to 2019-03-04

If anyone has the needed logs, link them here please :)

**Comment by ethanhs** [comment]
@nattofriends I think said they had some more.

**Comment by nikhiljha** [comment]
good enough
