### ISSUE TITLE
 haproxy → traefik

### ISSUE THREAD

**Issue by nikhiljha** [ocf/projects#40]
A lot of people have expressed interest in switching from haproxy to traefik (@fydai and @BernardZhao I think? and me 😄).

Traefik is cool because...
- it understands the underlying k8s architecture
- unblocks https://github.com/ocf/matrix/pull/12 since it can handle regular TCP/UDP and not only HTTP
- maybe some other reasons, add them in a comment if you think of any

**Comment by cg505** [comment]
this should probably be an issue in puppet

**Comment by nikhiljha** [comment]
closed -> new infra
