### ISSUE TITLE
new vm for public OCF Minecraft server

### ISSUE THREAD

**Issue by encadyma** [ocf/projects#47]
self-explanatory

**Comment by nikhiljha** [comment]
we should deploy it to kubernetes https://hub.docker.com/r/itzg/minecraft-server

**Comment by dkess** [comment]
Note that deploying non-HTTP things to our Kubernetes cluster is a bit involved, and not necessarily worth the effort.

**Comment by emmatyping** [comment]
I sadly don't we have the bandwidth to moderate a public minecraft server (though we can always spin up a server for staff)
