### ISSUE TITLE
beancount ficomm dashboard

### ISSUE THREAD

**Issue by amangalampalli** [ocf/projects#93]
Implement beancount for ficomm dashboard

**Comment by nikhiljha** [comment]
@Milotrince did this already i thought?

**Comment by yehchanyoo** [comment]
@Milotrince did work on it last semester, but she mentioned that the system still remained quite problematic with the system needing to be hosted locally, with finance information being hard to collect and update from Callink, etc. We are currently looking to see if we can improve beancount and incorporate beancount more into FiComm workflow.

**Comment by Milotrince** [comment]
@yehchanyoo @amangalampalli sorry I should have tagged you guys, I had already made a project card for this (see the automating finance card: https://github.com/orgs/ocf/projects/7?pane=issue&itemId=37304620)
https://github.com/ocf/finance-tools/issues/1

closing this issue, see the one linked above
